version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: immer
    versions:
    - 8.0.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.2.1
  - dependency-name: marked
    versions:
    - 2.0.0
  - dependency-name: "@ckeditor/ckeditor5-react"
    versions:
    - 3.0.0
    - 3.0.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@date-io/date-fns"
    versions:
    - 2.10.6
