export const SET_ENTITIES = 'SET_ENTITIES';
export const SET_ENTITIES_SHALLOW = 'SET_ENTITIES_SHALLOW';
export const SET_ENTITIES_ARRAY_CONCAT = 'SET_ENTITIES_ARRAY_CONCAT';
export const DELETE_ENTITIES_IN = 'DELETE_ENTITIES_IN';
