export const INITIALIZE_SNACKBAR = 'INITIALIZE_SNACKBAR';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const SET_SNACKBAR_DATA = 'SET_SNACKBAR_DATA';
